-- SCRIPT DE CREACION DE TABLAS CON PREFIJO usr_ - PYME BUÑUELOS

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABLA usr_ventas
CREATE TABLE IF NOT EXISTS public.usr_ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    unidades_vendidas INTEGER NOT NULL,
    unidades_pagadas INTEGER NOT NULL,
    unidades_bonificadas INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABLA usr_produccion
CREATE TABLE IF NOT EXISTS public.usr_produccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    unidades_vendidas INTEGER NOT NULL,
    produccion_estimada INTEGER NOT NULL,
    unidades_sobrantes INTEGER NOT NULL,
    porcentaje_merma NUMERIC(5,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA usr_clima
CREATE TABLE IF NOT EXISTS public.usr_clima (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    estado_clima TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABLA usr_publicidad
CREATE TABLE IF NOT EXISTS public.usr_publicidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    campaña TEXT,
    pauta_facebook NUMERIC(12,2),
    pauta_instagram NUMERIC(12,2),
    volantes_impresos NUMERIC(12,2),
    total_diario NUMERIC(12,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABLA usr_macro_anual
CREATE TABLE IF NOT EXISTS public.usr_macro_anual (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    smmlv NUMERIC(12,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TABLA usr_macro_mensual
CREATE TABLE IF NOT EXISTS public.usr_macro_mensual (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    inflacion_anual NUMERIC(5,2),
    desempleo NUMERIC(5,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. TABLA usr_macro_diario
CREATE TABLE IF NOT EXISTS public.usr_macro_diario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    trm NUMERIC(10,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TRIGGER PARA ACTUALIZAR updated_at AUTOMATICAMENTE
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DO $$
DECLARE
    t text;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name LIKE 'usr_%'
    LOOP
        EXECUTE format('CREATE OR REPLACE TRIGGER update_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();', t, t);
    END LOOP;
END $$;
